title: Victor Manuel Peláez
description: Stuff that I come across and find interesting.
author: Victor Manuel Peláez
email: victor.m.pelaez@outlook.com
phone: (+34) 647788580
github: https://github.com/VictorPelaez
about: working on it
#disqus_shortname: programming
#google_analytics: UA-31048387-6
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    #- icon: fa-facebook
    #  link: "https://www.facebook.com/tjamadar"
    #- icon: fa-twitter
    #  link: "https://twitter.com/tmjam3011"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/victormpelaez/"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/victorpelaez"

share:
  twitter_username: tmjam3011
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Blogs
      url: /blogs/
    - text: XML Feed
      url: /feed.xml
# url: "http://localhost:4000"
url: "https://tmjam.github.io/tauseef-blog"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
