title: Victor Manuel Peláez
description: Stuff that I come across and find interesting.
author: Victor Manuel Peláez
email: victor.m.pelaez@outlook.com
phone: (+34) 647788580
github: https://github.com/VictorPelaez
about: Data Scientist
#disqus_shortname: programming
#google_analytics: UA-31048387-6
avatar_url: /static/me_jpeg.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/victormpelaez/"
    - icon: fa-github
      link: "https://github.com/victorpelaez"
    - icon: fa-kaggle
      link: "https://www.kaggle.com/victormanuelpelaez"

share:
  twitter_username: tmjam3011
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Blogs
      url: /blogs/

url: "https://victorpelaez.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
